### ISSUE TITLE
an error occured after import this module

### ISSUE THREAD

**Issue by devinyan** [shiye515/react-m-carousel#1]
Hi , i just followed your guide to import this module,but there's an error occured during visiting page.
you can refer to below screen:

![image](https://user-images.githubusercontent.com/26291409/40961418-2044bef0-68d5-11e8-99b5-b3eb86bebcd8.png)

Thanks for your any answer.

**Comment by devinyan** [comment]
and i also refer to your example,but a error still showed like below:

![image](https://user-images.githubusercontent.com/26291409/40961718-fbf761e6-68d5-11e8-9063-63ee43246d27.png)

so maybe it need some extra file into your code.
Is it right!
Thanks.

**Comment by shiye515** [comment]
My webpack config libraryTarget has been set to wrong value, I publish a new version just now, With smaller size and better performance and a little api change. Please refer to the README
